### ISSUE TITLE
blynk-cloud SSL certificate error

### ISSUE THREAD

**Issue by roozbehf** [vshymanskyy/blynk-library-js#22]
I cannot connect to the blynk server using the secure connection. The SSL authorization fails with a `DEPTH_ZERO_SELF_SIGNED_CERT` error. I understand that this is most likely not a problem of this project, but since I could not find anything online, I thought to raise the issue here. Well, at least your examples currently fail on two machines I tested them on.

This is what I get if I run the *Usage Example* from your main README file:

```
Connecting to: blynk-cloud.com 8441
SSL authorization...
events.js:159
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (DEPTH_ZERO_SELF_SIGNED_CERT)
    at emit (events.js:157:17)
    at Blynk.error (/Users/trident/git/gitlab/blynk.agent/node_modules/blynk-library/blynk.js:571:8)
    at null.<anonymous> (/Users/trident/git/gitlab/blynk.agent/node_modules/blynk-library/blynk.js:534:48)
    at emitOne (events.js:90:13)
    at emit (events.js:182:7)
    at TLSSocket.<anonymous> (/Users/trident/git/gitlab/blynk.agent/node_modules/blynk-library/blynk-node.js:197:16)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at emitErrorNT (net.js:1250:8)
    at _combinedTickCallback (node.js:377:13)
```

**Comment by vshymanskyy** [comment]
Should be fixed now. Please update from npm

**Comment by roozbehf** [comment]
Thanks! works fine.
