### ISSUE TITLE
TypeError: "options" must be a string or an object, got number instead.

### ISSUE THREAD

**Issue by pratikd650** [vshymanskyy/blynk-library-js#26]
I am getting this error with the provided sample problem

  at getOptions (fs.js:50:11)
    at fs.readFileSync (fs.js:465:13)
    at Array.map (native)
    at exports.SslClient.connect (/home/pi/motor/node_modules/blynk-library/blynk-node.js:170:42)
    at doConnect (/home/pi/motor/node_modules/blynk-library/blynk.js:546:15)
    at Blynk.connect (/home/pi/motor/node_modules/blynk-library/blynk.js:559:5)
    at new Blynk (/home/pi/motor/node_modules/blynk-library/blynk.js:385:10)
    at Object.<anonymous> (/home/pi/motor/blynk-motor.js:9:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

I looked at the code carefully and it is at this line

`if (self.ca)   { opts.ca   = self.ca.map(fs.readFileSync); }`

fs.readFileSync takes options as second parameter, so it can't be used with map.

**Comment by vshymanskyy** [comment]
fixed

**Comment by DanielChisica** [comment]
Can anyone help me with this problem? I don't know how to fix it
