### ISSUE TITLE
Doesn't work in docker

### ISSUE THREAD

**Issue by YarekTyshchenko-awin** [vshymanskyy/blynk-library-js#3]
```
⌁41% [:~/Play/rpi/blynk] $ docker run --rm -it --name blink --privileged blink bash
root@7c75d93ca691:/# blynk.js xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
OnOff mode
Connecting to SSL: cloud.blynk.cc 8441
Connected, authorized
Blynk ready.
/usr/local/lib/node_modules/blynk-library/blynk-node.js:303
            this.blynk.sendMsg(MsgType.HW, null, ['dw', values[1], value]);
                ^
TypeError: Cannot read property 'blynk' of undefined
    at /usr/local/lib/node_modules/blynk-library/blynk-node.js:303:17
    at /node_modules/onoff/onoff.js:151:7
    at FSReqWrap.wrapper [as oncomplete] (fs.js:527:17)
```

Dockerfile:

```
FROM resin/rpi-raspbian:jessie

RUN echo "deb http://apt.adafruit.com/raspbian/ jessie main" >> /etc/apt/sources.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --force-yes node && \
    apt-get clean

RUN apt-get install -y python
RUN apt-get install -y build-essential
RUN npm install epoll && \
    npm install onoff

RUN npm install -g blynk-library

CMD ["blynk.js", "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
```

Ran with command:
```
docker build -t blink .
docker run --rm -it --name blink --privileged blink
```

**Comment by YarekTyshchenko-awin** [comment]
Yep. That fixes it, thanks Confirmed on a Rev 1 B pi
